[package]
name = "building-stuff"
version = "0.1.0"
authors = []

[dependencies]
amethyst = { version = "0.14.0", features = [ "vulkan" ] }
nphysics3d = "0.13.1"
# nphysics_testbed3d = "0.1"
ncollide3d = "0.21"
nalgebra = "0.19"
specs = "0.16.1"
winit = "0.21.0"
